

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-meta-sync-system
  labels:
    app.kubernetes.io/name: ingress-meta-sync
    app.kubernetes.io/part-of: ingress-meta-sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-meta-sync-controller
  namespace: ingress-meta-sync-system
  labels:
    app.kubernetes.io/name: ingress-meta-sync
    app.kubernetes.io/instance: controller
    app.kubernetes.io/part-of: ingress-meta-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-meta-sync
      app.kubernetes.io/instance: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-meta-sync
        app.kubernetes.io/instance: controller
    spec:
      serviceAccountName: ingress-meta-sync-controller
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: ${REGISTRY}/k8s-ingress-meta-sync:${TAG}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        args:
        - --leader-elect=true
        - --metrics-bind-address=:8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
