---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-meta-sync-controller
  namespace: ingress-meta-sync-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-meta-sync-controller
rules:
  # Allow access to the CRDs
  - apiGroups:
      - ingress-meta-sync.k8s.io
    resources:
      - providerconfigs
      - ingressconfigs
      - syncconfigs
      - providerconfigs/status
      - ingressconfigs/status
      - syncconfigs/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Allow access to Secrets to read API tokens
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  
  # Allow access to ConfigMaps for Istio configurations
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Allow access to Istio CRDs
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
      - virtualservices
      - gateways
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  
  # Allow access to Events for event recording
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-meta-sync-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-meta-sync-controller
subjects:
  - kind: ServiceAccount
    name: ingress-meta-sync-controller
    namespace: ingress-meta-sync-system
